# Generated by Django 5.2.7 on 2025-12-01 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description_ar', models.CharField(max_length=300)),
                ('description_en', models.CharField(max_length=300)),
                ('diet_rules', models.JSONField(default=[])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('active', 'Active'), ('high', 'High')], default='moderate', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='user',
            name='fluid_intake',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.DecimalField(decimal_places=2, default=160.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_duration',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_quality',
            field=models.IntegerField(choices=[(1, 'Deep'), (2, 'Stable'), (3, 'Mild'), (4, 'Light')], default=3),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=5),
        ),
        migrations.CreateModel(
            name='UserRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('medical', 'Medical'), ('budget', 'Budget'), ('prefrences', 'Prefrences'), ('avalblity', 'Avalablity'), ('other', 'Other')], default='other', max_length=20)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
