# Generated by Django 5.2.7 on 2025-12-01 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_medicalissues_user_activity_level_user_avatar_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrestriction',
            name='ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='users.medicalissues'),
        ),
    ]
