# Generated by Django 5.2.7 on 2025-12-01 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrestriction_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrestriction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restrictions', to=settings.AUTH_USER_MODEL),
        ),
    ]
