# Generated by Django 5.1 on 2024-12-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='UserRecipe',
        ),
    ]
