# Generated by Django 5.1 on 2024-12-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0003_recipe_userrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
