# Generated by Django 5.1 on 2024-12-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_plandetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
