# Generated by Django 5.1 on 2024-12-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0005_alter_plandetail_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='parent_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='diet.plandetail'),
        ),
    ]
