# Generated by Django 5.1 on 2024-12-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0006_alter_plandetail_parent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='media',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
