# Generated by Django 5.1 on 2024-12-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_plan_media_recipe_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nurtients',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='plan',
            name='media',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='media',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
