# Generated by Django 5.1 on 2024-12-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0008_recipe_nurtients_alter_plan_media_alter_recipe_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='nurtients',
            new_name='ingredients_nurtients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_nurtients',
            field=models.JSONField(default=list),
        ),
    ]
