# Generated by Django 5.2.7 on 2025-12-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healthHub', '0006_plandetail_detail_recipe_directions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('continues', 'Persistent state (weight, measurements)'), ('daily', 'Daily reset accumulation (water, calories)'), ('boolean', 'Yes/No event (cheat day, trained)'), ('scale', 'Ordered scale (1–5 exhaustion)'), ('category', 'Unordered choices (stressed, busy)')], default='continues', max_length=20)),
                ('options', models.JSONField(default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMetrics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('target', models.JSONField()),
                ('linkedPlan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackedPlan', to='healthHub.plan')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackedMetric', to='core.metric')),
            ],
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feedback', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_history', to='healthHub.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyAchivedMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(default=0)),
                ('start', models.JSONField(default=0)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalMetrics', to='core.trackedmetrics')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AchivedMetrics', to='core.userlog')),
            ],
        ),
    ]
