# Generated by Django 5.2.7 on 2025-12-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyachivedmetrics',
            name='start',
        ),
        migrations.AddField(
            model_name='trackedmetrics',
            name='start',
            field=models.JSONField(default=0),
        ),
    ]
