# Generated by Django 5.2.7 on 2025-12-26 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dailyachivedmetrics_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedmetrics',
            name='isPostive',
            field=models.BooleanField(default=True),
        ),
    ]
