# Generated by Django 5.2.7 on 2025-12-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_trackedmetrics_ispostive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedmetrics',
            name='target',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
