# Generated by Django 5.2.7 on 2025-12-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_trackedmetrics_target'),
        ('healthHub', '0006_plandetail_detail_recipe_directions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackedmetrics',
            name='linkedPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='healthHub.plan'),
        ),
    ]
