# Generated by Django 5.2.7 on 2025-11-10 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(blank=True, choices=[('diet', 'Diet'), ('exercise', 'Exercise'), ('full', 'Full')], max_length=20)),
                ('duration', models.DurationField()),
                ('goal', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='LinkedPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_plan', models.ForeignKey(blank=True, limit_choices_to={'plan_type': 'diet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_diet', to='healthHub.plan')),
                ('exercise_plan', models.ForeignKey(blank=True, limit_choices_to={'plan_type': 'exercise'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_exercise', to='healthHub.plan')),
                ('full_plan', models.OneToOneField(limit_choices_to={'plan_type': 'full'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_plan', to='healthHub.plan')),
            ],
        ),
        migrations.CreateModel(
            name='UserCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('shared', models.BooleanField(default=False)),
                ('media', models.JSONField(blank=True, default=list)),
                ('type', models.CharField(choices=[('recipe', 'Recipe'), ('plan', 'Plan')], max_length=10)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('prep_time', models.DurationField(blank=True, null=True)),
                ('serv', models.IntegerField(default=1)),
                ('ingredients', models.JSONField(blank=True, default=list)),
                ('directions', models.TextField(default='')),
                ('nutrients', models.JSONField(blank=True, default=dict)),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='healthHub.usercreation')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='healthHub.usercreation'),
        ),
        migrations.CreateModel(
            name='PlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=1)),
                ('parent_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_sections', to='healthHub.plandetail')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='healthHub.plan')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['plan', 'parent_section', 'order'], name='healthHub_p_plan_id_f91689_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usercreation',
            index=models.Index(fields=['creator', '-edited'], name='healthHub_u_creator_b26f29_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreation',
            index=models.Index(fields=['creator', 'type'], name='healthHub_u_creator_4c12d7_idx'),
        ),
        migrations.AddIndex(
            model_name='usercreation',
            index=models.Index(fields=['shared', '-edited'], name='healthHub_u_shared_d2e72c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercreation',
            unique_together={('creator', 'name')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['category'], name='healthHub_r_categor_9aa552_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['plan_type'], name='healthHub_p_plan_ty_2f8346_idx'),
        ),
    ]
