# Generated by Django 5.2.7 on 2025-11-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
