# Generated by Django 5.2.7 on 2025-11-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthHub', '0002_usercreation_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plan',
            name='healthHub_p_plan_ty_2f8346_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='healthHub_r_categor_9aa552_idx',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AlterField(
            model_name='linkedplan',
            name='diet_plan',
            field=models.ForeignKey(blank=True, limit_choices_to={'base__category': 'diet'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_diet', to='healthHub.plan'),
        ),
        migrations.AlterField(
            model_name='linkedplan',
            name='exercise_plan',
            field=models.ForeignKey(blank=True, limit_choices_to={'base__category': 'exercise'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_as_exercise', to='healthHub.plan'),
        ),
        migrations.AlterField(
            model_name='linkedplan',
            name='full_plan',
            field=models.OneToOneField(limit_choices_to={'base__category': 'full'}, on_delete=django.db.models.deletion.CASCADE, related_name='linked_plan', to='healthHub.plan'),
        ),
        migrations.AddIndex(
            model_name='usercreation',
            index=models.Index(fields=['category'], name='healthHub_u_categor_c41127_idx'),
        ),
    ]
