# Generated by Django 5.2.7 on 2025-11-16 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthHub', '0003_remove_plan_healthhub_p_plan_ty_2f8346_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreation',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
