# Generated by Django 5.2.7 on 2025-11-19 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthHub', '0004_usercreation_favorite_alter_plan_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercreation',
            options={},
        ),
        migrations.RemoveField(
            model_name='plandetail',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='directions',
        ),
    ]
