# Generated by Django 5.2.7 on 2025-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthHub', '0005_alter_usercreation_options_remove_plandetail_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandetail',
            name='detail',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='recipe',
            name='directions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
